import '../datamodels/ExerciseModel.dart';

List<ExerciseModel> allexercises=[
  ExerciseModel("exohealgreen", "Flexi-Grab Exercise",
      "This exercise involves gripping and releasing a soft or pliable object, such as a stress ball or sponge, using the fingers and thumb. It helps improve grip strength and coordination.",
      "8 min"),
  ExerciseModel("exohealgreen", "Grip Strengthening Drill",
      "This drill focuses on strengthening the muscles involved in gripping by squeezing a handheld device or resistance ball for a set duration or number of repetitions.",
      "8 min"),
  ExerciseModel("exohealgreen", "Wrist Rotation Routine",
      "This routine entails rotating the wrist in both clockwise and counterclockwise directions to improve range of motion and flexibility in the wrist joint.",
      "8 min"),
  ExerciseModel("exohealgreen", "Palm Press Challenge",
      "In this exercise, the individual presses the palms together with varying degrees of pressure, aiming to improve coordination and strength in the muscles of the hands and wrists.",
      "8 min"),
  ExerciseModel("exohealgreen", "Thumb Flex Workout",
      "This workout targets the muscles of the thumb by performing flexion and extension movements, enhancing mobility and control of the thumb.",
      "8 min"),
  ExerciseModel("exohealgreen", "Pinch and Hold Drill",
      "The pinch and hold drill involves using the thumb and fingers to pinch and hold small objects (e.g., clothespins, coins) for a specified duration, promoting finger strength and precision.",
      "8 min"),
  ExerciseModel("exohealgreen", "Finger Stretch Sequence",
      "This sequence consists of stretching the fingers and thumb in different directions to increase flexibility and reduce stiffness in the hand and fingers.",
      "8 min"),
  ExerciseModel("exohealgreen", "Hand Roll Therapy",
      "Hand roll therapy involves rolling a cylindrical object (e.g., therapy putty, foam roller) between the palms and fingers, improving grip strength and mobility.",
      "8 min"),
  ExerciseModel("exohealgreen", "Knuckle Mobility Circuit",
      "This circuit focuses on exercises to increase mobility and flexibility in the knuckles, including bending and straightening the fingers.",
      "8 min"),
  ExerciseModel("exohealgreen", "Digit Dexterity Drill",
      "This drill aims to enhance finger dexterity and control by performing various finger movements, such as tapping, flicking, and tracing patterns.",
      "8 min"),
  ExerciseModel("exohealgreen", "Tactile Sensation Session",
      "This session involves stimulating tactile sensation in the hands and fingers through activities such as exploring different textures or objects with the fingertips.",
      "8 min"),
  ExerciseModel("exohealgreen", "Grasp and Release Reps",
      "In this exercise, the individual repeatedly grasps and releases objects of varying sizes and shapes, improving hand coordination and control.",
      "8 min"),
  ExerciseModel("exohealgreen", "Palm Flexibility Flow",
      "This flow focuses on improving flexibility and mobility in the palms and fingers through gentle stretching and movement exercises.",
      "8 min"),
  ExerciseModel("exohealgreen", "Finger Spread Stretch",
      "The finger spread stretch involves spreading the fingers apart as far as possible and then bringing them back together, enhancing finger flexibility and range of motion.",
      "8 min"),
  ExerciseModel("exohealgreen", "Precision Grasp Practice",
      "This practice involves performing precise grasping movements, such as picking up small objects or manipulating tools, to improve fine motor skills and coordination.",
      "8 min"),

  ExerciseModel("exohealgreen", "Finger Tip Exercise",
      "Make sure you have bluetooth on your device turned on", "8 min"),
  ExerciseModel("exohealgreen", "Haptic Exercise Exercise",
      "Make sure you have bluetooth on your device turned on", "8 min"),
  ExerciseModel("exohealgreen", "Grabbing Exercise",
      "Make sure you have bluetooth on your device turned on", "8 min"),
  ExerciseModel("exohealgreen", "Mirror Therapy",
      "Make sure you have bluetooth on your device turned on", "8 min"),
];